### ISSUE TITLE
deploying to heroku

### ISSUE THREAD

**Issue by notmarkmiranda** [notmarkmiranda/pokerrank_angular#6]
does anyone know how to deploy to heroku? i tried `ng build` but it didn't work.

**Comment by s-espinosa** [comment]
Was able to push to Heroku and get it to start (used `heroku ps:scale web=1` per [this](https://devcenter.heroku.com/articles/getting-started-with-nodejs#deploy-the-app) documentation), but got a memory error. From the logs:

```
Process running mem=570M(111.4%)
Error R14 (Memory quota exceeded)
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

Tried to upgrade to hobby, but that seemed to be getting similar errors. Web wisdom seems to point to a memory leak of some sort? Not sure where that would be.

**Comment by s-espinosa** [comment]
Item 7 in [this](https://blog.heroku.com/node-habits-2016) Heroku article seems to indicate that we need to be more aggressive with garbage collection to get things to work on Heroku. Unfortunately, it seems that the particular solution they offer is related to running `node server.js` with some additional flags. We don't have a `server.js` file and we're using the Angular CLI commands instead of `node` to start the server, so trying to use that particular solution seems to be a no go. Looked for similar flags to pass to `ng serve`, but it seems like the options there are a little more limited (at least based on output from `ng help`). This is all according to some limited research and what I was able to gather from the `package.json` file, so let me know if I'm completely off base here.

Any reason not to deploy to GitHub Pages per the [Angular CLI docs](https://github.com/angular/angular-cli)?

**Comment by ghost** [comment]
@s-espinosa not against deploying to github pages. also, maybe now is a good time to move one step further and go with the endgame of having it on Digital Ocean or something similar?
